language: generic 
sudo: required
services:
    - docker
before_install:
    - docker build -t peterblockman/docker-react -f Dockerfile.dev .
script:
    - docker run -e CI=true peterblockman/docker-react npm run test