version: '3'
services:
  web:
    build: 
      context: . #where we want the files and folders for this image to be pulled from
      dockerfile: Dockerfile.dev # force using tghe dev file
    ports:
      - "3000:3000"
    volumes:
        - /app/node_modules
        - .:/app
  tests:
    build: 
      context: . #where we want the files and folders for this image to be pulled from
      dockerfile: Dockerfile.dev # force using tghe dev file
    volumes:
        - /app/node_modules
        - .:/app
    command: ["yarn", "run", "test"]